name: "build docker image"
description: "builds docker image"
author: "eDACT"
inputs:
  docker_registry_url:
    description: "URL of the docker registry, no trailing slashes"
    default: "docker.pkg.github.com"
    required: false
  docker_registry_user:
    description: "user for registry"
    default: "publisher"
    required: false
  docker_registry_token:
    description: "token for registry"
    required: true
  working_directory:
    description: "working directory the action should be performed in"
    default: "."
    required: false
  image_name:
    description: "name of the image"
    required: true
  image_tags:
    description: "list of tags, seperated by comma"
    required: true
  build_base_tag:
    description: "tag for images the new image should be built upon"
    default: stable
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
