name: "build docker image"
description: "builds docker image"
author: "eDACT"
inputs:
  docker_registry_url:
    description: "URL of the docker registry, no trailing slashes"
    default: "docker.pkg.github.com"
    required: false
  working_directory:
    description: "working directory the action should be performed in"
    default: "."
    required: false
  image_name:
    description: "name of the image"
    required: true
  image_tags:
    description: "list of tags, seperated by comma"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
