name: "build docker image"
description: "builds docker image"
author: "eDACT"
inputs:
  docker_registry_url:
    description: "URL of the docker registry, no trailing slashes"
    default: "docker.pkg.github.com"
  image_name:
    description: "name of the image"
    required: true
  image_tags:
    description: "list of tags, seperated by comma"
    default: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.docker_registry_url}}
    - ${{ inputs.image_name }}
    - ${{ inputs.image_tags }}
    - ${{ inputs.release_tags }}
