name: "build npm package"
description: "builds npm package"
author: "eDACT"
inputs:
  npm_registry_url:
    description: "URL of the npm registry"
    default: "https://npm.pkg.github.com/"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.npm_registry_url }}
