name: "create .npmrc file"
description: "creates .npmrc file needed for npm installs"
author: "eDACT"
inputs:
  npm_registry_url:
    description: "URL of the npm registry, no trailing slashes"
    default: "npm.pkg.github.com"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.npm_registry_url }}
