name: "lint openapi file"
description: "lints a given openapi file with spectral"
author: "eDACT"
inputs:
  input_path:
    description: "path to file that should linted"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
