name: "bundle openapi spec"
description: "bundles multiple openapi files into one"
author: "eDACT"
inputs:
  input_dir:
    description: "directory of file that should be dereferenced"
    default: "defaultdir"
    required: false
  output_dir:
    description: "directory of output file"
    default: "defaultdir"
    required: false
  input_filename:
    description: "name of file that should be dereferenced"
    default: "defaultname"
    required: false
  output_filename:
    description: "name of output file"
    default: "defaultname"
    required: false
  output_filetype:
    description: "json or yaml"
    default: "yaml"
    required: false
  dereference:
    description: "boolean wether to fully derefence the json"
    default: "true"
    required: false
  delete_files:
    description: boolean wether  to delete files
    default: "true"
    required: false
  delete_glob:
    description: "glob pattern to delete child openapi files relative to input path"
    default: "**/*.oas.*"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
