name: "bundle openapi spec"
description: "bundles multiple openapi files into one"
author: "eDACT"
inputs:
  input_path:
    description: "path to file that should be dereferenced"
    default: "defaultpath"
    required: false
  output_path:
    description: "path to output file"
    default: "defaultpath"
    required: false
  output_filetype:
    description: "json or yaml"
    default: "yaml"
    required: false
  dereference:
    description: "boolean wether to fully derefence the json"
    default: "false"
    required: false
  delete_files:
    description: boolean wether  to delete files
    default: "false"
    required: false
  delete_glob:
    description: "glob pattern to delete child openapi files relative to input path"
    default: "**/*.oas.*"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
